#:schema node_modules/wrangler/config-schema.json
name = "vishal-logistics"
main = "@astrojs/cloudflare/entrypoints/server"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./dist"

[[send_email]]
name = "SEB"

[vars]
DESTINATION_EMAIL = "info@vishallogistics.in"

[observability]
enabled = true